version: '3.7'

services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: symfony_test
            MYSQL_USER: root
            MYSQL_PASSWORD:
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${DEFAULT_TIMEZONE}
        ports:
            - "9000:9000"
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./docker/logs/symfony:/var/www/symfony/app/logs
        links:
            - mysql
        extra_hosts:
            - "symfony.local:127.0.0.1"
    nginx:
        build: docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
